Enrollment-240840116069

Aim:Study the Data Analytics lifecycle and perform data acquisition from CSV,
Excel, and JSON files using Pandas.

Step-1: Import the pandas Libary

In [ ]:
import pandas as pd #import the pandas library to it

Step-2: Create a sample data

In [ ]:
data = {
    "ID": [101,102,103,104,105,106,107],
    "Name": ["Rahul","priya","Amit","Riya","Karan","Krisha","Harry"],
    "Age": [20,21,19,20,22,24,28],
    "city" : ["Surat","Navsari","Valsad","Bharuch","Surat","Gandhinagar","Ahmedabad"],
    "Marks":[85,92,78,88,81,84,90]
}
df = pd.DataFrame(data) #create a dataframe
df #dispalys the created dataset

    ID    Name  Age         city  Marks
0  101   Rahul   20        Surat     85
1  102   priya   21      Navsari     92
2  103    Amit   19       Valsad     78
3  104    Riya   20      Bharuch     88
4  105   Karan   22        Surat     81
5  106  Krisha   24  Gandhinagar     84
6  107   Harry   28    Ahmedabad     90

Step-3: Create a dataframe

In [ ]:
df = pd.DataFrame(data) #create a dataframe
df #dispalys the created dataset

    ID    Name  Age         city  Marks
0  101   Rahul   20        Surat     85
1  102   priya   21      Navsari     92
2  103    Amit   19       Valsad     78
3  104    Riya   20      Bharuch     88
4  105   Karan   22        Surat     81
5  106  Krisha   24  Gandhinagar     84
6  107   Harry   28    Ahmedabad     90

Step-4: Saves data as a csv file

In [ ]:
df.to_csv("student.csv",index=False) # Export to CSV without saving the default row numbers
print("csv file created successfully.")

csv file created successfully.

Step-5: Saves data as an excel file

In [ ]:
df.to_excel("student.xlsx",index=False) # Export to excel without saving the default row numbers
print("Excel file created successfullly")

Excel file created successfullly

Step-6: Saves data as a JSON file

In [ ]:
df.to_json("student.json",orient="records",index=4) #Export to json format
print("json file created successfullly")

json file created successfullly

Step-7 Read the csv file

In [ ]:
df_csv = pd.read_csv("student.csv") # Load the csv file data into memory as a structured DataFrame
df_csv

    ID    Name  Age         city  Marks
0  101   Rahul   20        Surat     85
1  102   priya   21      Navsari     92
2  103    Amit   19       Valsad     78
3  104    Riya   20      Bharuch     88
4  105   Karan   22        Surat     81
5  106  Krisha   24  Gandhinagar     84
6  107   Harry   28    Ahmedabad     90

Step-8: Read the excel file

In [ ]:
df_excel = pd.read_excel("student.xlsx") #Load data from excel sheet into memory as a structured dataframe
df_excel

    ID    Name  Age         city  Marks
0  101   Rahul   20        Surat     85
1  102   priya   21      Navsari     92
2  103    Amit   19       Valsad     78
3  104    Riya   20      Bharuch     88
4  105   Karan   22        Surat     81
5  106  Krisha   24  Gandhinagar     84
6  107   Harry   28    Ahmedabad     90

Step-9:Head

In [ ]:
df_csv.head() #Shows the first 5 rows from the dataframe

    ID   Name  Age     city  Marks
0  101  Rahul   20    Surat     85
1  102  priya   21  Navsari     92
2  103   Amit   19   Valsad     78
3  104   Riya   20  Bharuch     88
4  105  Karan   22    Surat     81

Step-10 Tail()

In [ ]:
df_csv.tail() # Shows the last 5 rows

    ID    Name  Age         city  Marks
2  103    Amit   19       Valsad     78
3  104    Riya   20      Bharuch     88
4  105   Karan   22        Surat     81
5  106  Krisha   24  Gandhinagar     84
6  107   Harry   28    Ahmedabad     90

Step-11 Display the information

In [ ]:
df_csv.info() # Get a quick summary of the data (size, columns, and missing values)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      7 non-null      int64
 1   Name    7 non-null      object
 2   Age     7 non-null      int64
 3   city    7 non-null      object
 4   Marks   7 non-null      int64
dtypes: int64(3), object(2)
memory usage: 412.0+ bytes

Step-12 Display the descriptive format

In [ ]:
df_csv.describe() #Display descriptive stats for numeric column

               ID        Age      Marks
count    7.000000   7.000000   7.000000
mean   104.000000  22.000000  85.428571
std      2.160247   3.109126   4.961759
min    101.000000  19.000000  78.000000
25%    102.500000  20.000000  82.500000
50%    104.000000  21.000000  85.000000
75%    105.500000  23.000000  89.000000
max    107.000000  28.000000  92.000000

Step-13 Display the number of rows and columns

In [ ]:
df_csv.shape #Shows the number of rows and columns in tuple datatype as output

(7, 5)

Step-14 Display the columnsof the dataset

In [ ]:
df_csv.columns #Display columns name

Index(['ID', 'Name', 'Age', 'city', 'Marks'], dtype='object')

Step-15 Display the datatypes of the columns

In [ ]:
df_csv.dtypes #Display the datatypes of each columns

ID        int64
Name     object
Age       int64
city     object
Marks     int64
dtype: object

Step-16 Give the count of the null values.

In [ ]:
df_csv.isnull().sum() #isnull():checks for missing values provides boolean answer isnull.sum():count missing values in column.

ID       0
Name     0
Age      0
city     0
Marks    0
dtype: int64

Step-17 Display only the Marks and Age column's data

In [ ]:
df_csv[["Marks" , "Age"]]#Dis only the specified col

   Marks  Age
0     85   20
1     92   21
2     78   19
3     88   20
4     81   22
5     84   24
6     90   28

Step-18 Display the students data with marks greater than 80

In [ ]:
df_csv[df_csv["Marks"]>80]#dis only rows where condition is true

    ID    Name  Age         city  Marks
0  101   Rahul   20        Surat     85
1  102   priya   21      Navsari     92
3  104    Riya   20      Bharuch     88
4  105   Karan   22        Surat     81
5  106  Krisha   24  Gandhinagar     84
6  107   Harry   28    Ahmedabad     90

Step-19 Display the average marks of students

In [ ]:
df_csv["Marks"].mean()#mean() computes avg of selected col

np.float64(85.42857142857143)

Step-20 Sort the values in descending order of marks

In [ ]:
df_csv.sort_values(by="Marks", ascending=False)#sort() sort the dataset, ascending=false in des orders of marks, by specifies the parameter of sorting

    ID    Name  Age         city  Marks
1  102   priya   21      Navsari     92
6  107   Harry   28    Ahmedabad     90
3  104    Riya   20      Bharuch     88
0  101   Rahul   20        Surat     85
5  106  Krisha   24  Gandhinagar     84
4  105   Karan   22        Surat     81
2  103    Amit   19       Valsad     78

Step-21 Display the final dataset

In [ ]:
print(df_csv) #Display dataset

    ID    Name  Age         city  Marks
0  101   Rahul   20        Surat     85
1  102   priya   21      Navsari     92
2  103    Amit   19       Valsad     78
3  104    Riya   20      Bharuch     88
4  105   Karan   22        Surat     81
5  106  Krisha   24  Gandhinagar     84
6  107   Harry   28    Ahmedabad     90