Enrollment-240840116069

**Practical-2 | Perform data inspection, cleaning, handling, mising values duplicates rewmoval and data transformation using pandas**

In [ ]:
import pandas as pd
data={
    "ID":[101,102,103,104,104,105,106,107],
    "Name":["Rahul","Priya","Amit",None,"Riya","Ajay","Naresh","Jenil"],
    "Age":[20,21,None,20,20,22,23,28],
    "City":["Surat","Navsari","Surat","Bharuch","Bharuch","Navsari","Surat","Ahemdabad"],
    "Marks":[85,None,78,88,88,81,90,93]
}
df = pd.DataFrame(data)
df

    ID    Name   Age       City  Marks
0  101   Rahul  20.0      Surat   85.0
1  102   Priya  21.0    Navsari    NaN
2  103    Amit   NaN      Surat   78.0
3  104    None  20.0    Bharuch   88.0
4  104    Riya  20.0    Bharuch   88.0
5  105    Ajay  22.0    Navsari   81.0
6  106  Naresh  23.0      Surat   90.0
7  107   Jenil  28.0  Ahemdabad   93.0

Step-3 Display the first five rows of dataset

In [ ]:
df.head() #displays the first 5 rows

    ID   Name   Age     City  Marks
0  101  Rahul  20.0    Surat   85.0
1  102  Priya  21.0  Navsari    NaN
2  103   Amit   NaN    Surat   78.0
3  104   None  20.0  Bharuch   88.0
4  104   Riya  20.0  Bharuch   88.0

Step-4 Display last five rows of dataset

In [ ]:
df.tail() #displays the last 5 rows

    ID    Name   Age       City  Marks
3  104    None  20.0    Bharuch   88.0
4  104    Riya  20.0    Bharuch   88.0
5  105    Ajay  22.0    Navsari   81.0
6  106  Naresh  23.0      Surat   90.0
7  107   Jenil  28.0  Ahemdabad   93.0

Step-5 Display detailed information of dataset

In [ ]:
df.info() # Get a quick summary of the data (size, columns, and missing values)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      8 non-null      int64
 1   Name    7 non-null      object
 2   Age     7 non-null      float64
 3   City    8 non-null      object
 4   Marks   7 non-null      float64
dtypes: float64(2), int64(1), object(2)
memory usage: 452.0+ bytes

Step-6 Display statistical information of dataset

In [ ]:
df.describe() #Display descriptive stats for numeric column

           ID        Age      Marks
count    8.00   7.000000   7.000000
mean   104.00  22.000000  86.142857
std      2.00   2.886751   5.209881
min    101.00  20.000000  78.000000
25%    102.75  20.000000  83.000000
50%    104.00  21.000000  88.000000
75%    105.25  22.500000  89.000000
max    107.00  28.000000  93.000000

Display the dimensions(rows,columns) of dataset

In [ ]:
df.shape #Shows the number of rows and columns in tuple datatype as output

(8, 5)

 Display the datatypes of each columns

In [ ]:
df.dtypes #Display the datatypes of each columns

ID         int64
Name      object
Age      float64
City      object
Marks    float64
dtype: object

Display all the columns of the dataset

In [ ]:
df.columns  #Display columns name

Index(['ID', 'Name', 'Age', 'City', 'Marks'], dtype='object')

Step-4 Check missing values for all columns

In [ ]:
df.isnull() #Checks for the null values and provide boolean answer

      ID   Name    Age   City  Marks
0  False  False  False  False  False
1  False  False  False  False   True
2  False  False   True  False  False
3  False   True  False  False  False
4  False  False  False  False  False
5  False  False  False  False  False
6  False  False  False  False  False
7  False  False  False  False  False

Print the count of null values for each column

In [ ]:
df.isnull().sum() #Give the count of null values in each column

ID       0
Name     1
Age      1
City     0
Marks    1
dtype: int64

Print the total number of null values for whole dataset

In [ ]:
df.isnull().sum().sum() #give the count of total null values in the dataset

np.int64(3)

Step-5 Fill missing values

In [ ]:
df["Marks"] = df["Marks"].fillna(df["Marks"].mean()) #fillna() replaces the missing values with the calculated average
#mean() for average
df

    ID    Name   Age       City      Marks
0  101   Rahul  20.0      Surat  85.000000
1  102   Priya  21.0    Navsari  86.142857
2  103    Amit   NaN      Surat  78.000000
3  104    None  20.0    Bharuch  88.000000
4  104    Riya  20.0    Bharuch  88.000000
5  105    Ajay  22.0    Navsari  81.000000
6  106  Naresh  23.0      Surat  90.000000
7  107   Jenil  28.0  Ahemdabad  93.000000

Fill missing *age*

In [ ]:
df["Age"] = df["Age"].fillna(df["Age"].mean()) #fillna() replaces the missing values with the calculated average
df

    ID    Name   Age       City      Marks
0  101   Rahul  20.0      Surat  85.000000
1  102   Priya  21.0    Navsari  86.142857
2  103    Amit  22.0      Surat  78.000000
3  104    None  20.0    Bharuch  88.000000
4  104    Riya  20.0    Bharuch  88.000000
5  105    Ajay  22.0    Navsari  81.000000
6  106  Naresh  23.0      Surat  90.000000
7  107   Jenil  28.0  Ahemdabad  93.000000

Fill Missing Names

In [ ]:
df["Name"] = df["Name"].fillna("Unknown") #fillna() replaces the missing values with the Unknown
df

    ID     Name   Age       City      Marks
0  101    Rahul  20.0      Surat  85.000000
1  102    Priya  21.0    Navsari  86.142857
2  103     Amit  22.0      Surat  78.000000
3  104  Unknown  20.0    Bharuch  88.000000
4  104     Riya  20.0    Bharuch  88.000000
5  105     Ajay  22.0    Navsari  81.000000
6  106   Naresh  23.0      Surat  90.000000
7  107    Jenil  28.0  Ahemdabad  93.000000

Step-6 Detect the duplicate records

In [ ]:
df.duplicated() #Shows which rows are duplicated

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
dtype: bool

Count the number of duplicate rows

In [ ]:
df.duplicated().sum() #Gives the count of dupliacted rows

np.int64(0)

Step-7 Remove the duplicate records

In [ ]:
df.drop_duplicates() #Drop the duplicate rows from the dataset

    ID     Name   Age       City      Marks
0  101    Rahul  20.0      Surat  85.000000
1  102    Priya  21.0    Navsari  86.142857
2  103     Amit  22.0      Surat  78.000000
3  104  Unknown  20.0    Bharuch  88.000000
4  104     Riya  20.0    Bharuch  88.000000
5  105     Ajay  22.0    Navsari  81.000000
6  106   Naresh  23.0      Surat  90.000000
7  107    Jenil  28.0  Ahemdabad  93.000000

Rename a column

In [ ]:
df.rename(columns={"Marks":"Score"}, inplace=True) #rename():renames the name of the column ,inplace=True replaces it permanently
df

    ID     Name   Age       City      Score
0  101    Rahul  20.0      Surat  85.000000
1  102    Priya  21.0    Navsari  86.142857
2  103     Amit  22.0      Surat  78.000000
3  104  Unknown  20.0    Bharuch  88.000000
4  104     Riya  20.0    Bharuch  88.000000
5  105     Ajay  22.0    Navsari  81.000000
6  106   Naresh  23.0      Surat  90.000000
7  107    Jenil  28.0  Ahemdabad  93.000000

Step-9 Change the datatypes

Convert age column into integer

In [ ]:
df["Age"] = df["Age"].astype(int) #astype():Converts the age column's datatype into integer
df

    ID     Name  Age       City      Score
0  101    Rahul   20      Surat  85.000000
1  102    Priya   21    Navsari  86.142857
2  103     Amit   22      Surat  78.000000
3  104  Unknown   20    Bharuch  88.000000
4  104     Riya   20    Bharuch  88.000000
5  105     Ajay   22    Navsari  81.000000
6  106   Naresh   23      Surat  90.000000
7  107    Jenil   28  Ahemdabad  93.000000

Step-10 Create a new name column final score and in that add 5 grace marks to every student's existing score

In [ ]:
df["Final Score"] = df["Score"]+5 # Create a column final score and add 5 gracing marks to the existing file
df

    ID     Name  Age       City      Score  Final Score
0  101    Rahul   20      Surat  85.000000    90.000000
1  102    Priya   21    Navsari  86.142857    91.142857
2  103     Amit   22      Surat  78.000000    83.000000
3  104  Unknown   20    Bharuch  88.000000    93.000000
4  104     Riya   20    Bharuch  88.000000    93.000000
5  105     Ajay   22    Navsari  81.000000    86.000000
6  106   Naresh   23      Surat  90.000000    95.000000
7  107    Jenil   28  Ahemdabad  93.000000    98.000000

Step-11: Convert text to uppercase
Convert all students names to uppercaese

In [ ]:
df["Name"] = df["Name"].str.upper() #str.upper() converts the text to uppercase
df

    ID     Name  Age       City      Score  Final Score
0  101    RAHUL   20      Surat  85.000000    90.000000
1  102    PRIYA   21    Navsari  86.142857    91.142857
2  103     AMIT   22      Surat  78.000000    83.000000
3  104  UNKNOWN   20    Bharuch  88.000000    93.000000
4  104     RIYA   20    Bharuch  88.000000    93.000000
5  105     AJAY   22    Navsari  81.000000    86.000000
6  106   NARESH   23      Surat  90.000000    95.000000
7  107    JENIL   28  Ahemdabad  93.000000    98.000000

Step-12: Convert all city names to lowercase

In [ ]:
df["City"] = df["City"].str.lower()
df

    ID     Name  Age       City      Score  Final Score
0  101    RAHUL   20      surat  85.000000    90.000000
1  102    PRIYA   21    navsari  86.142857    91.142857
2  103     AMIT   22      surat  78.000000    83.000000
3  104  UNKNOWN   20    bharuch  88.000000    93.000000
4  104     RIYA   20    bharuch  88.000000    93.000000
5  105     AJAY   22    navsari  81.000000    86.000000
6  106   NARESH   23      surat  90.000000    95.000000
7  107    JENIL   28  ahemdabad  93.000000    98.000000

Step-13: Remove all spaces from the city column

In [ ]:
df["City"] = df["City"].str.strip() #Romves the whitespaces(trailing/leading) from the city column
df

    ID     Name  Age       City      Score  Final Score
0  101    RAHUL   20      surat  85.000000    90.000000
1  102    PRIYA   21    navsari  86.142857    91.142857
2  103     AMIT   22      surat  78.000000    83.000000
3  104  UNKNOWN   20    bharuch  88.000000    93.000000
4  104     RIYA   20    bharuch  88.000000    93.000000
5  105     AJAY   22    navsari  81.000000    86.000000
6  106   NARESH   23      surat  90.000000    95.000000
7  107    JENIL   28  ahemdabad  93.000000    98.000000

Step-14: sort the dataset

In [ ]:
df.sort_values(by="Score" ,ascending=False) #Sort the dataset in the descending order by marks

    ID     Name  Age       City      Score  Final Score
7  107    JENIL   28  ahemdabad  93.000000    98.000000
6  106   NARESH   23      surat  90.000000    95.000000
3  104  UNKNOWN   20    bharuch  88.000000    93.000000
4  104     RIYA   20    bharuch  88.000000    93.000000
1  102    PRIYA   21    navsari  86.142857    91.142857
0  101    RAHUL   20      surat  85.000000    90.000000
5  105     AJAY   22    navsari  81.000000    86.000000
2  103     AMIT   22      surat  78.000000    83.000000

Step-15: Save the clean dataset

In [ ]:
df.to_csv("Cleaned_Students.csv", index=False) #Saves the dataset as Cleaned_Students.csv file