Enrollment:240840116069

**Practical 3**
**Apply filtering, sorting, aggregation and groupby operation **

In [ ]:
#importing the pandas and the numpy library
import pandas as pd
import numpy as np
#Creating the database
data={
    "Emp_ID":[101, 102, 103, 104, 105, 106, 107, 108],
    "Name":["Rahul","Priya","Amit","Riya","Karan","Neha","Vivek","Pooja"],
    "Department":["IT","HR","IT","Finance","HR","Finance","IT","HR"],
    "City":["Surat","Navsari","Surat","Valsad","Surat","Navsari","Valsad","Surat"],
    "Salary":[45000,38000,52000,48000,40000,51000,60000,42000],
    "Experience":[2,1,5,4,2,6,8,3]
}
#Creating a datafarme of the database
df=pd.DataFrame(data)

Step-1

In [ ]:
#Displaying the dataframe which we have created
df

   Emp_ID   Name Department     City  Salary  Experience
0     101  Rahul         IT    Surat   45000           2
1     102  Priya         HR  Navsari   38000           1
2     103   Amit         IT    Surat   52000           5
3     104   Riya    Finance   Valsad   48000           4
4     105  Karan         HR    Surat   40000           2
5     106   Neha    Finance  Navsari   51000           6
6     107  Vivek         IT   Valsad   60000           8
7     108  Pooja         HR    Surat   42000           3

Step-2

2.1 Display emp from it dept

In [ ]:
#Displaying the employees from IT department
df[df["Department"]=="IT"]

   Emp_ID   Name Department    City  Salary  Experience
0     101  Rahul         IT   Surat   45000           2
2     103   Amit         IT   Surat   52000           5
6     107  Vivek         IT  Valsad   60000           8

2.2 Display employees with salary greater than 50000

In [ ]:
#Displaying the employees with salary more than 50000
df[df["Salary"]>50000]

   Emp_ID   Name Department     City  Salary  Experience
2     103   Amit         IT    Surat   52000           5
5     106   Neha    Finance  Navsari   51000           6
6     107  Vivek         IT   Valsad   60000           8

2.3 Display employees fron Surat

In [ ]:
#Displaying the employees belongs Surat
df[df[("City")]=="Surat"]

   Emp_ID   Name Department   City  Salary  Experience
0     101  Rahul         IT  Surat   45000           2
2     103   Amit         IT  Surat   52000           5
4     105  Karan         HR  Surat   40000           2
7     108  Pooja         HR  Surat   42000           3

2.4 Display employees from IT department and having salary more than 50000

In [ ]:
#Displaying the employees from IT department with salary more than 50000
df[(df["Department"]=="IT")&(df["Salary"]>50000)]# We have used AND operator

   Emp_ID   Name Department    City  Salary  Experience
2     103   Amit         IT   Surat   52000           5
6     107  Vivek         IT  Valsad   60000           8

Step-3 Sort the data

3.1 Sort salaries in ascending order

In [ ]:
#Sorting the values using the sort() in ascending order
df.sort_values('Salary', ascending=True)

   Emp_ID   Name Department     City  Salary  Experience
1     102  Priya         HR  Navsari   38000           1
4     105  Karan         HR    Surat   40000           2
7     108  Pooja         HR    Surat   42000           3
0     101  Rahul         IT    Surat   45000           2
3     104   Riya    Finance   Valsad   48000           4
5     106   Neha    Finance  Navsari   51000           6
2     103   Amit         IT    Surat   52000           5
6     107  Vivek         IT   Valsad   60000           8

3.2 Sort salaries in descending order

In [ ]:
#Displaying salaries in descending using ascending=False
df.sort_values('Salary', ascending=False)

   Emp_ID   Name Department     City  Salary  Experience
6     107  Vivek         IT   Valsad   60000           8
2     103   Amit         IT    Surat   52000           5
5     106   Neha    Finance  Navsari   51000           6
3     104   Riya    Finance   Valsad   48000           4
0     101  Rahul         IT    Surat   45000           2
7     108  Pooja         HR    Surat   42000           3
4     105  Karan         HR    Surat   40000           2
1     102  Priya         HR  Navsari   38000           1

3.3 Sort employees by Department and salary

In [ ]:
# Sort department in ascending order then set salary fron ach department in descending order
df.sort_values(['Department', 'Salary'], ascending=[True, False])

   Emp_ID   Name Department     City  Salary  Experience
5     106   Neha    Finance  Navsari   51000           6
3     104   Riya    Finance   Valsad   48000           4
7     108  Pooja         HR    Surat   42000           3
4     105  Karan         HR    Surat   40000           2
1     102  Priya         HR  Navsari   38000           1
6     107  Vivek         IT   Valsad   60000           8
2     103   Amit         IT    Surat   52000           5
0     101  Rahul         IT    Surat   45000           2

Step-4 Perform aggregation

4.1 Calculate total salary

In [ ]:
#Using sum() calculate all employees salary
df["Salary"].sum()

np.int64(376000)

4.2 Calculate average salary

In [ ]:
#Get the average salary using mean()
df["Salary"].mean()

np.float64(47000.0)

4.3 Find maximum salary

In [ ]:
# Get maximum salary using max()
df["Salary"].max()

60000

4.4 Find the minimum salary

In [ ]:
#Get the minimum salary using min()
df["Salary"].min()

38000

4.5Count the employees

In [ ]:
#Get the count of total employees using the count() on employees id
df["Emp_ID"].count()

np.int64(8)

Step-5 Perform groupby operations

5.1 Average salary by department

In [ ]:
#Group employees by department
#Get average using mean()
df.groupby('Department')['Salary'].mean()

Department
Finance    49500.000000
HR         40000.000000
IT         52333.333333
Name: Salary, dtype: float64

5.2 Total salary by department

In [ ]:
# Get total salary paid by each department
df.groupby('Department')['Salary'].mean()

Department
Finance    49500.000000
HR         40000.000000
IT         52333.333333
Name: Salary, dtype: float64

5.3 Maximum salary by department

In [ ]:
# Get maximum salary by deaparyment using max()
df.groupby('Department')['Salary'].max()

Department
Finance    51000
HR         42000
IT         60000
Name: Salary, dtype: int64

5.4 Count of employees by department

In [ ]:
# Get count of employees in department
df.groupby('Department')['Emp_ID'].count()

Department
Finance    2
HR         3
IT         3
Name: Emp_ID, dtype: int64

Average salary by city

In [ ]:
# Group by employees by city and use mean()
df.groupby('City')['Salary'].mean()

City
Navsari    44500.0
Surat      44750.0
Valsad     54000.0
Name: Salary, dtype: float64

Step-6 Multiple aggregate function

In [ ]:
# Apply the multiple statistical functions to the slary column
df.groupby('Department')['Salary'].agg(['mean','sum','max','min','count'])

                    mean     sum    max    min  count
Department
Finance     49500.000000   99000  51000  48000      2
HR          40000.000000  120000  42000  38000      3
IT          52333.333333  157000  60000  45000      3

Step-7 Save the dataset as csv file

In [ ]:
#Convert the dataframe into csv file
df.to_csv("employees_data.csv",index=False)
print("Csv file saved successfully.")

Csv file saved successfully.

Step-8 Download the csv filw

In [ ]:
#importthe files module from google colab
from google.colab import files
#Download the csv file
files.download("employees_data.csv")
print("File downloadd successfully")

File downloadd successfully